idmp_rleng: 3
idmp_tree_hl_min: 0.00625
idmp_tree_hl_max: 1.6
idmp_tree_hl_clust: 0.0125
idmp_tree_hl_init: 0.8
idmp_map_scale: 900
idmp_obs_skip: 10
idmp_filt_outl: False

idmp_depth_input: False
idmp_dual_cam: False
idmp_pub_pcl: True
idmp_world_frame: "base_link"
idmp_pcl_topic: "/camera/depth_registered/points"
# idmp_pcl_topic: "/fused_points_filt"
idmp_caminfo_topic: 
  - ["/camera_info", "camera_rgb_optical_frame"]

idmp_dynamic: False
idmp_fusion: False

idmp_dyn_tresh: 0.05
idmp_fus_min: 0.0005
idmp_fus_max: 0.005
